controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute
app_verify_email:
  path: "/verify-email/{id}/{hash}"
  controller: 'App\Controller\VerifyEmailController::verify'
  methods: ["GET"]
